version: '3.1'

services:
  gobarber:
    container_name: gobarber
    build:
      context: .
    volumes:
      - ./src:/gobarber/src
      - ./tmp:/gobarber/tmp
    ports:
      - 3333:3333
    depends_on:
      - db
    networks:
      - gobarber-network

  db:
    container_name: gobarber-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gostack_gobarber
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - gobarber-network

volumes:
  db-data:

networks:
  gobarber-network:
    driver: bridge
