version: '3.1'

services:
  gobarber:
    build:
      context: .
    volumes:
      - ./src:/gobarber/src
    ports:
      - 3333:3333

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gostack_gobarber
    ports:
      - 5432:5432
